services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=database1'
      - 'POSTGRES_PASSWORD=secret123'
      - 'POSTGRES_USER=user1'
    ports:
      - '5401:5432'
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
