services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=yunotalktrack'
      - 'POSTGRES_PASSWORD=yunotalk123'
      - 'POSTGRES_USER=YunoDev'
    ports:
      - '5400:5432'
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
